### ISSUE TITLE
Cluster node hosted via embedded can't find address of the application

### ISSUE THREAD

**Issue by Eykhler** [sakno/dotNext#11] opened 2020-08-13 10:49 UTC
Hi,

I ran into some issue while configuring Kestrel through the application config file using the `server.urls` parameter.
If the StartUp class takes longer than RaftHttCluster to start, it cannot find the server address and the application stops with the message:
```
g:\work\VSNET\github\dotNext\src\examples\RaftNode\bin\Debug\netcoreapp3.1>RaftNode.exe http 3262
Unhandled exception. DotNext.Net.Cluster.Consensus.Raft.RaftProtocolException: Configured list of members in cluster doesn't contain address of entire application
   at DotNext.Net.Cluster.Consensus.Raft.Http.RaftHttpCluster.StartAsync(CancellationToken token) in g:\work\VSNET\github\dotNext\src\cluster\DotNext.AspNetCore.Cluster\Net\Cluster\Consensus\Raft\Http\RaftHttpCluster.cs:line 138
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at RaftNode.Program.Main(String[] args) in g:\work\VSNET\github\dotNext\src\examples\RaftNode\Program.cs:line 143
   at RaftNode.Program.<Main>(String[] args)
```

I think this is related to the issue https://github.com/aspnet/Hosting/issues/1390 which says that `server.Features.Get<IServerAddresses>()` gets populated after StartUp is done.

It's easy to reproduce:
1. add the parameter to the configuration dictionary `{"server.urls", "http: // localhost: 3262"}`
2. configure Kestrel without specifying the port `UseKestrel()`
3. add a delay at the end of the Startup.ConfigureServices (..) method `System.Threading.Thread.Sleep (10000)`
4. compile and run the application with http protocol

The only workaround is setting up a Kestrel listener address and port while building the host, isn't it?

**Comment by sakno** [comment] 2020-08-13 12:03
@Eykhler , the current solution is not elegant, correct. However, it's working for most scenarios. Probably, it's time to return back and fix it. aspnet/Hosting#1390 is one of the show stoppers. However, the issue contains a hint: if `IHostedService` depends on `IServer` instance then `IServerAddresses` should be available at the time of `StartAsync`. `RaftHttpCluster` implements exactly in the same way. But now I'm looking at your issue and can conclude that such an approach is not working for some reason.

What can I offer here:
* Wait for `IServerAddresses` in a loop inside of `RaftHttpCluster.StartAsync`. Not elegant, because `IServerAddresses` may be unavailableall the time. IDK, is there any _startup timeout_ in generic host? If no, the app may freeze infinitely.
* Examine configuration and use `server.urls` if `IServerAddresses` is unavailable. This approach is not good, because embedded mode uses underlying HTTP server (`IServer` instance) which may differs from Kestrel and `server.urls` configuration property can be ignored by it.

**Comment by sakno** [comment] 2020-08-13 12:39
@Eykhler , I was unable to reproduce you issue. Delay in `ConfigureServices` just _delays_ execution of `RaftHttpCluster.StartAsync` method. Kestrel is always started at that point and provided `IServerAddresses` is correct. _server.urls_ is ignored by Kestrel. By default, it uses two addresses:
* http://localhost:5000
* http://localhost:5001

Here is my modified `UseAspNetCoreHost` method from RaftNode example:
```csharp
 var configuration = new Dictionary<string, string>
            {
                {"partitioning", "false"},
                {"lowerElectionTimeout", "150" },
                {"upperElectionTimeout", "300" },
                {"server.urls", "http://localhost:3265"},
                {"members:0", "https://localhost:3262"},
                {"members:1", "https://localhost:3263"},
                {"members:2", "https://localhost:3264"},
                {"requestJournal:memoryLimit", "5" },
                {"requestJournal:expiration", "00:01:00" }
            };
            if (!string.IsNullOrEmpty(persistentStorage))
                configuration[SimplePersistentState.LogLocation] = persistentStorage;
            return new HostBuilder().ConfigureWebHost(webHost =>
            {
                webHost.UseKestrel()
                // .UseKestrel(options =>
                // {
                //     options.ListenLocalhost(port, listener => listener.UseHttps(LoadCertificate()));
                // })
                .UseStartup<Startup>();
            })
            .ConfigureLogging(builder => builder.AddConsole().SetMinimumLevel(LogLevel.Error))
            .ConfigureAppConfiguration(builder => builder.AddInMemoryCollection(configuration))
            .JoinCluster()
            .Build()
            .RunAsync();
```

It means that trick with `IHostedService` is working and `IServer` always in started state when `RaftHttpCluster.StartAsync` called.

**Comment by Eykhler** [comment] 2020-08-13 12:50
Thanks for the clarification!

Now I am setting up the Kestrel listener during host build, this is not a problem for me.

The main disadvantage is that it works fine under the debugger, but when running without a debugger connected, it crashes, and only examining the source code allows you to understand the real problem.

Maybe you can use [IHostLifetime.WaitForStartAsync(CancellationToken)](https://docs.microsoft.com/en-US/dotnet/api/microsoft.extensions.hosting.ihostlifetime.waitforstartasync?view=dotnet-plat-ext-3.1&viewFallbackFrom=netstandard-2.1) method at the start of the RaftHttpCluster to delay start (it's maybe configured).

Maybe highlight this point in the documentation to save time for other developers!?

**Comment by sakno** [comment] 2020-08-13 12:54
`WaitForStartAsync` will be recursive call, because it waits for all `IHostedService`s. Could you please provide source code of modified `UseAspNetCoreHost` method?

**Comment by sakno** [comment] 2020-08-13 12:56
If you're using `UseKestrel` method without parameters as shown above then Kestrel doesn't know anything about _server.urls_ configuration parameter and just ignore it. Instead, it uses two endpoins by default which are not in the list of members. Therefore, you get this exception.

**Comment by Eykhler** [comment] 2020-08-13 13:06
Yes you are right, Kestrel doesn't know about the `server.urls` parameter, my example is not up to date.
I will try to modify the example using a config file and reproduce the error.

**Comment by sakno** [comment] 2020-08-13 13:18
You can reproduce it using in-memory configuration instead of file. It's transparent for Kestrel and other ASP.NET Core components.

**Comment by Eykhler** [comment] 2020-08-13 15:12
Sorry, I can't reproduce the issue with RaftNode example project right now.
But in my project, I see the following console output:
```
dbug: Aurus.CmsPlus.Backend.Service.Startup[0]
      Startup completed
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://192.168.201.34:6000
```
the URL http://192.168.201.34:6000 is the value of the `server.urls` configuration parameter, and the `Startup completed` is the last line of the Startup.Configure() method. So the Kestrel listener URL is replaced after Startup.

**Comment by sakno** [comment] 2020-08-13 17:03
`Startup completed` log message is in Startup class. Its configuration methods are called by Host synchronously. But `RaftHttpCluster.StartAsync` is not calling by Startup class. It's called afterwards by constructed Host as well as `IServer`.

Message `Now listening on: http://192.168.201.34:6000` is produced by [GenericWebHostService](https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L126) inside of `StartAsync` method. As a result, HTTP server is always started and initialized before `RaftHttpCluster.StartAsync` is called.

You can check this with the following:
* Write you own hosted service (derived from `BackgroundService` or implements `IHostedService` directly)
* Inject `IServer` via constructor and save it to the field
* Prints `IServerAddresses` in your implementation of `StartAsync` method

At the moment, I cannot confirm this issue as a bug. So I'm closing it.

**Closed by sakno** 2020-08-13 17:03 UTC
Labels: wontfix
